### ISSUE TITLE
Changeable week count in WeekCalendar

### ISSUE THREAD

**Issue by yakaska** [kizitonwose/Calendar#406]
So are you looking for implementing a calendar type where user can switch from 1 week -> 2 week -> month? Please let us know if it already can be done.
### One week mode
![1week](https://user-images.githubusercontent.com/49792007/198851678-eafff738-e841-4d31-bdb4-1cfd6c51e16e.jpg)
### Two week mode
![2week](https://user-images.githubusercontent.com/49792007/198851679-72f61cf9-1785-4a12-8fd7-d8db5efd998d.jpg)
### Month mode
![month](https://user-images.githubusercontent.com/49792007/198851681-88ba6bfb-642c-437b-bacc-abb1bc14b686.jpg)

**Comment by kizitonwose** [comment]
It is difficult to justify the work to be done for the two-row week since not many people use it. I don't plan to support it right now but maybe if more people request it in the future, I'd look into it. You can keep using version [1.1.0](https://github.com/kizitonwose/Calendar/tree/1.1.0) for this use case.
