### ISSUE TITLE
Call MonthScrollListener before binding to views

### ISSUE THREAD

**Issue by dgudim** [kizitonwose/Calendar#408]
I currently use MonthScrollListener to load some data for the currently visible month, the data is displayed on the day view containers, so to actually show the data I have to call ```notifyCalendarChanged()``` after loading the data. An option to call MonthScrollListener before binding to all views would eliminate this double update.

**Comment by kizitonwose** [comment]
It would not solve the problem if this is a remote call to load the data as it will not return before binding the views. 

Basically, this would happen:
- notifyScroll()
- remoteCall -- start
- bindViews()
- remoteCall -- end

Also, the method you should use in this case is the more efficient `notifyMonthChanged()`, no need to reload the entire calendar if you only loaded data for a month.

Finally, you should consider loading the data for one or two months ahead for a better user experience.

**Comment by dgudim** [comment]
However, calling ```notifyMonthChanged()``` fades the calendar for like half a second, how can I remowe that at least?

**Comment by kizitonwose** [comment]
> This is not a remote call, it is synchronous so it would fix it.

I assumed if it's a synchronous call, you would not have this problem since you can already load the data upfront, but I guess that depends on how you provide the data. That said, if loading 3 months is noticeable, then best to make it async.

> However, calling notifyMonthChanged() fades the calendar for like half a second, how can I remove that at least?

I think it is the default item animator from RecyclerView, I should disable that in the next release.

Disable it with `calendarView.itemAnimator = null`

**Comment by dgudim** [comment]
I still want to load the data for the visible month immediately and for others in the background, because calling the fetch function for one month takes 50ms and rebinding all views takes about 40ms, so its either 50 + 40 + 40 or 50 + 50 + 40 but the data loads immediately. Having a listener fire before rebind would still be nice. Maybe don't change the current one but add another or make it a boolean flag. Thanks.

**Comment by kizitonwose** [comment]
On further thought, this cannot happen because of how RecyclerView works, the item view is bound *before* it is brought on screen. Calling the scroll listener at that point would be wrong, however, maybe a second listener would be great for this.

If you currently have a month header, the `bind()` method in the `MonthHeaderFooterBinder` would be the right place for this as it is called first before the body content is bound.

**Comment by dgudim** [comment]
Many thanks for you help, I do have a month header, so will use that for now. Waiting for the next release :)
