### ISSUE TITLE
Month is Incorrect Height when using OutDateStyle.EndOfRow and non-Sunday firstDayOfWeek

### ISSUE THREAD

**Issue by hscissors** [kizitonwose/Calendar#428]
### Library information:
 - Version: 2.0.1
 - Compose

### Describe the bug**
If we set the the `firstDayOfWeek` in the `CalendarState` to Monday (e.g. `daysOfWeek(firstDayOfWeek = DayOfWeek.MONDAY)`) and then use `OutDateStyle.EndOfRow`. December 2022 is the wrong height. If we change the `firstDayOfWeek` to Sunday, the height is correct. 

### Expected behavior (if applicable)
When using `EndOfRow` month height should always wrap.

![endOfWeekMonday](https://user-images.githubusercontent.com/1406478/206043297-a0913092-4777-4329-972b-02b13a0c60a8.png)
![endOfWeekSunday](https://user-images.githubusercontent.com/1406478/206043304-28988e25-e794-450a-acae-a4d8e72eed58.png)

**Comment by kizitonwose** [comment]
Hi, this is not a bug but because the off-screen month which has 6 rows is being measured by LazyRow, see the screenshot below.

<img src="https://user-images.githubusercontent.com/15170090/207257914-73fa8e4e-03b7-4002-9382-8b9c291ff608.png" width="500">

Since you have square days, this should be easy to fix, you need to use a fixed height => 
`(calendarWidth / 7) * weeksInVisibleMonth`, where 7 is the days in a week.

With that, we have the result below:

<img src="https://user-images.githubusercontent.com/15170090/207259119-c147bf8b-6e88-4d55-b553-89dbf728855e.png" width="500">

I have added the code with this fix [here](https://github.com/kizitonwose/Calendar/blob/ft_fixed_height/sample/src/main/java/com/kizitonwose/calendar/sample/compose/Example1Page.kt#L81) so you can take a look.

There is an [upcoming feature](https://issuetracker.google.com/issues/172029355) in LazyList which should hopefully allow customizing the off-screen items. I say `hopefully` because I am not sure if the API is purely for prefetching data without actually using those indices for measurement.

**Comment by hscissors** [comment]
Ah great. Thank you for the detailed follow-up!

**Comment by hscissors** [comment]
One thing I noticed in your sample is you reference `CalendarState.weeksInVisibleMonth` but there seems to only be `firstVisibleMonth` and `lastVisibleMonth`. If there was a property that was `currentVisible` that would switch, perhaps 50% through a drag that would be incredibly useful.

**Comment by kizitonwose** [comment]
`weeksInVisibleMonth` is a computed property:

```kotlin
 val visibleMonth = rememberFirstVisibleMonthAfterScroll(monthState)
 val weeksInVisibleMonth = visibleMonth.weekDays.count()
```
Regarding the 50% drag, take a look at how we calculate the fully visible month [here](https://github.com/kizitonwose/Calendar/blob/d7c91eafc03651435c4de4950b842aba821908b3/sample/src/main/java/com/kizitonwose/calendar/sample/compose/Utils.kt#L137), the logic can be adjusted to your desired percentage and then you can use that to determine the height.

**Comment by kizitonwose** [comment]
Looks like this can be closed. Let me know if you need further assistance.
