### ISSUE TITLE
Help for using a fork on android studio

### ISSUE THREAD

**Issue by V41ER** [kizitonwose/Calendar#527]
### Library information:
 - Version: 2.4.1 Forked
 - View or Compose module: View

### Question:
Hello @kizitonwose !
I'd like to use my fork in another kotlin project in the same way as I already use the main library.
The problem is that when I try to do this with the implementation in my kotlin project, it can't find the library.

Here's what I'm adding to my graddle:
`implementation 'com.Trecobat:Calendar5DaysPerWeek:view:1.0.1'`

The link to my repo git :
https://github.com/Trecobat/Calendar5DaysPerWeek

If anyone can help me simply by using a fork with Android Studio, I'd love it :D !

**Comment by kizitonwose** [comment]
That is because the fork is not published, you can either publish to maven central or [Jitpack](https://jitpack.io/docs/) (this is easier)

**Comment by V41ER** [comment]
Hey !

Could you explain how to do it? I haven't found the solution for over a month and the tutorials are pretty vague on the subject.

Or maybe there are tutorials on this subject that you think would be interesting?

**Comment by kizitonwose** [comment]
[This](https://medium.com/@EmreKaydu/how-to-do-publish-android-library-in-jitpack-io-968e634843eb) looks straightforward.

**Comment by kizitonwose** [comment]
I will close this, we can continue the discussion if you need further assistance.

**Comment by kizitonwose** [comment]
FYI: I needed to quickly publish a library to JitPack today and [these](https://github.com/kizitonwose/material-components-android/commit/2ce0afe1c30b94f6b971b0fb8738c33aa28c4742) were the only changes I needed to make. The first build failed because JitPack builds with `Java 8` by default, but after adding a `jitpack.yml` file with `Java 17` specified as the Java version, the build succeded. Just thought this may help you.

<img width="609" alt="Screenshot" src="https://github.com/kizitonwose/Calendar/assets/15170090/19cf10d2-fa34-4f87-b572-feaa3cdbc30a">
